# site_name: TIV
# site_url: https://zkote47.github.io/smnvs
# theme:
#   name: material
#   custom_dir: overrides
#   palette:
#     primary: deep purple

# site_author: zkote

# markdown_extensions:
#   - admonition
#   - pymdownx.details
#   - pymdownx.superfences


site_name: TIV
site_description: Персональная база знаний моего DevOps-становления
site_author: zkote_47
site_url: https://zkote47.github.io/smnvs

theme:
  name: material
  language: ru
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.action.edit
  palette:
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Тёмная тема
    - scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Светлая тема
  icon:
    repo: fontawesome/brands/github

repo_name: zkote_47/smnvs
repo_url: https://zkote47.github.io/smnvs
edit_uri: edit/main/docs/

# nav:
#   - Главная: index.md
#   - DevOps:
#     - Docker: devops/docker.md
#     - Kubernetes: devops/kubernetes.md
#   - Книги и статьи: reading.md
#   - О проекте: about.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:material.extensions.emoji.twemoji
  #     emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # - pymdownx.tasklist:
  #     custom_checkbox: true
  - toc:
      permalink: true
  - attr_list
  - md_in_html

plugins:
  - search


extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://zkote47.github.io/smnvs
    - icon: fontawesome/brands/telegram
      link: https://t.me/socsichka
  version:
    provider: mike

# copyright: |
#   &copy; 2024 Ваше Имя - Содержимое доступно по 
#   <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank">лицензии CC BY-SA 4.0</a>